<div class="row">
    <div class="col-12 py-5 text-center"><h1>Developer Bookmark - InsanityMeetsHH <a href="https://github.com/InsanityMeetsHH/developer-bookmark" target="_blank"><i class="fab fa-inverse fa-github"></i></a></h1></div>
</div>
<div class="row text-center align-items-center justify-content-center mb-3 filter">
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-primary" data-class="btn-primary">Software</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-success" data-class="btn-success">Generator</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-info" data-class="btn-info">Tool</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-secondary" data-class="btn-secondary">Documentation</button>
    </div>
</div>
<div class="row text-center align-items-center justify-content-center bookmark">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://getcomposer.org/" role="button" target="_blank">Composer</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://packagist.org/" role="button" target="_blank">Packagist</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://nodejs.org/" role="button" target="_blank">Node.js</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://www.npmjs.com/" role="button" target="_blank">NPM</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-info" href="https://andrew.hedges.name/experiments/aspect_ratio/" role="button" target="_blank">Aspect Ratio</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-secondary" href="https://www.w3schools.com/cssref/css_selectors.asp" role="button" target="_blank">CSS Selector</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-info" href="https://developers.facebook.com/tools/debug/" role="button" target="_blank">Facebook Debugger</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-secondary" href="https://caniuse.com/" role="button" target="_blank">Can I Use</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="http://www.loremipsum.de/" role="button" target="_blank">Lorem Ipsum</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="https://wppb.me/" role="button" target="_blank">Wordpress Plugin</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="http://www.colorzilla.com/gradient-editor/" role="button" target="_blank">CSS Gradient</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="http://www.timestampgenerator.com/" role="button" target="_blank">Timestamp</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://daneden.github.io/animate.css/" role="button" target="_blank">Animate.css</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://getbootstrap.com/" role="button" target="_blank">Bootstrap 4</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://fontawesome.com/" role="button" target="_blank">Fontawesome 5</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="http://kenwheeler.github.io/slick/" role="button" target="_blank">Slick Carousel</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="https://placeholder.com/" role="button" target="_blank">Placeholder Image</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-success" href="https://www.gitignore.io/" role="button" target="_blank">gitignore</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-secondary" href="https://devhints.io/" role="button" target="_blank">Devhints</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-primary" href="https://www.adminer.org/" role="button" target="_blank">Adminer</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-info" href="https://pandao.github.io/editor.md/en.html" role="button" target="_blank">Markdown Editor</a>
    </div>
</div>
