<div class="row">
    <div class="col-12 py-5 text-center"><h1>Developer Bookmark <a href="https://github.com/Codelinered/developer-bookmark" target="_blank"><i class="fab fa-inverse fa-github"></i></a></h1></div>
</div>
<div class="row text-center align-items-center justify-content-center mb-3 filter">
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-code" data-class="code">Source Code</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-generator" data-class="generator">Generator</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-tool" data-class="tool">Tool</button>
    </div>
    <div class="col-12 col-sm-6 col-lg-3 pb-3">
        <button type="button" class="btn btn-block btn-docu" data-class="docu">Documentation</button>
    </div>
</div>
<div class="row text-center align-items-center justify-content-center mb-3 bookmark">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://getcomposer.org/" role="button" target="_blank">Composer</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code" href="https://packagist.org/" role="button" target="_blank">Packagist</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://nodejs.org/" role="button" target="_blank">Node.js</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code" href="https://www.npmjs.com/" role="button" target="_blank">NPM</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://andrew.hedges.name/experiments/aspect_ratio/" role="button" target="_blank">Aspect Ratio</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://www.w3schools.com/cssref/css_selectors.asp" role="button" target="_blank">CSS Selector</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://developers.facebook.com/tools/debug/" role="button" target="_blank">Facebook Debugger</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://caniuse.com/" role="button" target="_blank">Can I Use</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="http://www.loremipsum.de/" role="button" target="_blank">Lorem Ipsum</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://daneden.github.io/animate.css/" role="button" target="_blank">Animate.css</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="https://wppb.me/" role="button" target="_blank">Wordpress Plugin</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="http://jackiebalzer.com/color" role="button" target="_blank">SASS Color</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://getbootstrap.com/" role="button" target="_blank">Bootstrap</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="http://www.colorzilla.com/gradient-editor/" role="button" target="_blank">CSS Gradient</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://fontawesome.com/" role="button" target="_blank">Fontawesome</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="http://www.timestampgenerator.com/" role="button" target="_blank">Timestamp</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="http://kenwheeler.github.io/slick/" role="button" target="_blank">Slick Carousel</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://twig.symfony.com/" role="button" target="_blank">Twig</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://www.adminer.org/" role="button" target="_blank">Adminer</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://pandao.github.io/editor.md/en.html" role="button" target="_blank">Markdown Editor</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://www.slimframework.com/" role="button" target="_blank">Slim</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="http://symfony.com/" role="button" target="_blank">Symfony</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="https://dummyimage.com/" role="button" target="_blank">Dummy Image</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://developers.google.com/analytics/devguides/collection/analyticsjs/events" role="button" target="_blank">Analytics Events</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-code-docu" href="https://jquery.com/" role="button" target="_blank">jQuery</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="https://placeholder.com/" role="button" target="_blank">Placeholder Image</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="https://www.gitignore.io/" role="button" target="_blank">gitignore</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://devhints.io/" role="button" target="_blank">Devhints</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://keepachangelog.com/" role="button" target="_blank">Changelog</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://semver.org/spec/v2.0.0.html" role="button" target="_blank">Semantic Versioning</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://picular.co/" role="button" target="_blank">Picular</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://brandcolors.net/" role="button" target="_blank">BrandColors</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="https://developers.google.com/tag-manager/devguide" role="button" target="_blank">GTM Dev Guide</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-docu" href="http://shouldiprefix.com/" role="button" target="_blank">Should I Prefix CSS</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-generator" href="https://fonts.google.com/" role="button" target="_blank">Google Web Font</a>
    </div>
</div>
<div class="row text-center mb-3">
    <div class="col-12">
        <h2>Google Chrome</h2>
    </div>
</div>
<div class="row text-center align-items-center justify-content-center bookmark special-group">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/udomainflag/eklbfdpploakpkdakoielobggbhemlnm" role="button" target="_blank">uDomainFlag</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/colorzilla/bhlhnicpbhignbdhedgjhgdocnmhomnp" role="button" target="_blank">ColorZilla</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/emmet-review/epejoicbhllgiimigokgjdoijnpaphdp" role="button" target="_blank">Emmet Re:view</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/pix-to-pix-pixel-perfect/binboaimbgchaamickjnhgjdccohndin" role="button" target="_blank">PerfectPixel</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/rest-web-service-client/ecjfcmddigpdlehfhdnnnhfgihkmejin" role="button" target="_blank">Rest Client</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/tag-assistant-by-google/kejbdjndbnbjgmefkgdddjlbokphdefk" role="button" target="_blank">Google Tag Manager</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/page-ruler/emliamioobfffbgcfdchabfibonehkme" role="button" target="_blank">Page Ruler</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://chrome.google.com/webstore/detail/user-agent-switcher-for-g/ffhkkpnppgnfaobgihpdblnhmmbodake" role="button" target="_blank">User-Agent Switcher</a>
    </div>
</div>
<div class="row text-center mb-3">
    <div class="col-12">
        <h2>Mozilla FireFox</h2>
    </div>
</div>
<div class="row text-center align-items-center justify-content-center bookmark special-group">
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/flagfox/" role="button" target="_blank">Flagfox</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/browser-ruler/" role="button" target="_blank">Page Ruler</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/perfectpixel/" role="button" target="_blank">PerfectPixel</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/restclient/" role="button" target="_blank">Rest Client</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/colorzilla/" role="button" target="_blank">ColorZilla</a>
    </div>
    <div class="col-12 col-sm-6 col-md-4 col-lg-3 pb-3">
        <a class="btn btn-block btn-tool" href="https://addons.mozilla.org/de/firefox/addon/user-agent-switcher-revived/" role="button" target="_blank">User-Agent Switcher</a>
    </div>
</div>
